import styles from "./page.module.css";

export default function Home() {
  return (
    <main className={styles.main}>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
      <div>aaaaaaaaaaaaaaaaaaa</div>
    </main>
  );
}
